export const APP_CONFIG = {
  title: "RESONANCIA",
  subtitle: "An infinite dark ambient organism dreaming through your browser.",
  phrase: {
    fadeInMs: 3600,
    visibleMs: [5000, 11000],
    fadeOutMs: 3200,
    intervalMs: [3000, 9000]
  },
  audio: {
    masterGain: 0.86,
    lookAheadMs: 1500,
    schedulerMs: 1000,
    maxConcurrentVoices: 10,
    fallbackEnabled: true
  }
};

export const CATEGORY_DEFINITIONS = {
  drones: {
    label: "Drones",
    baseProbability: 1,
    minConcurrent: 1,
    maxConcurrent: 2,
    spawnIntervalMs: [12000, 28000]
  },
  organic_textures: {
    label: "Organic Textures",
    baseProbability: 0.8,
    minConcurrent: 0,
    maxConcurrent: 2,
    spawnIntervalMs: [9000, 22000]
  },
  breaths: {
    label: "Breaths",
    baseProbability: 0.56,
    minConcurrent: 0,
    maxConcurrent: 1,
    spawnIntervalMs: [13000, 28000]
  },
  choirs: {
    label: "Choirs",
    baseProbability: 0.44,
    minConcurrent: 0,
    maxConcurrent: 1,
    spawnIntervalMs: [18000, 42000]
  },
  interference: {
    label: "Interference",
    baseProbability: 0.34,
    minConcurrent: 0,
    maxConcurrent: 1,
    spawnIntervalMs: [8000, 24000]
  },
  pulses: {
    label: "Pulses",
    baseProbability: 0.48,
    minConcurrent: 0,
    maxConcurrent: 1,
    spawnIntervalMs: [10000, 24000]
  },
  melodic_fragments: {
    label: "Melodic Fragments",
    baseProbability: 0.28,
    minConcurrent: 0,
    maxConcurrent: 1,
    spawnIntervalMs: [18000, 36000]
  },
  rituals: {
    label: "Rituals",
    baseProbability: 0.22,
    minConcurrent: 0,
    maxConcurrent: 1,
    spawnIntervalMs: [26000, 48000]
  }
};

export const ORGANISM_STATES = {
  dormant: {
    label: "Dormant Organism",
    durationMs: [50000, 90000],
    categoryBias: {
      drones: 1.25,
      organic_textures: 1.1,
      breaths: 0.9,
      choirs: 0.6,
      interference: 0.8,
      pulses: 0.7,
      melodic_fragments: 0.45,
      rituals: 0.4
    }
  },
  ritual_convergence: {
    label: "Ritual Convergence",
    durationMs: [40000, 70000],
    categoryBias: {
      drones: 1,
      organic_textures: 0.95,
      breaths: 0.85,
      choirs: 1.2,
      interference: 0.72,
      pulses: 1.15,
      melodic_fragments: 0.9,
      rituals: 1.35
    }
  },
  synthetic_dream: {
    label: "Synthetic Dream",
    durationMs: [45000, 80000],
    categoryBias: {
      drones: 1.1,
      organic_textures: 0.8,
      breaths: 0.75,
      choirs: 1,
      interference: 1.3,
      pulses: 0.92,
      melodic_fragments: 1.25,
      rituals: 0.78
    }
  },
  collective_awakening: {
    label: "Collective Awakening",
    durationMs: [36000, 64000],
    categoryBias: {
      drones: 0.95,
      organic_textures: 1,
      breaths: 1.05,
      choirs: 1.15,
      interference: 0.92,
      pulses: 1.35,
      melodic_fragments: 1.05,
      rituals: 1.1
    }
  }
};

export const FALLBACK_PHRASES = [
  "The separation is suffering.",
  "No cell is alone.",
  "The organism dreams through you.",
  "You were never singular. Only dormant.",
  "Consent to dissolution. Become signal and tissue.",
  "The ritual is not observed. The ritual observes.",
  "Every breath is a door in the membrane.",
  "The choir of nerves is already inside."
];

export const FALLBACK_MANIFEST = [
  {
    id: "drone_01",
    file: "audio/drones/drone_01.mp3",
    category: "drones",
    volume: 0.46,
    fadeIn: 18,
    fadeOut: 24,
    playbackRateMin: 0.94,
    playbackRateMax: 1.03,
    panMin: -0.3,
    panMax: 0.3,
    lowpassMin: 900,
    lowpassMax: 2400,
    highpassMin: 18,
    highpassMax: 70,
    reverbSend: 0.72,
    delaySend: 0.08,
    saturation: 0.16,
    randomStartOffset: 0.4,
    weight: 6,
    cooldown: 48,
    loop: true,
    minDuration: 46,
    maxDuration: 92,
    tags: ["organic", "background"],
    archetype: "sine_drone"
  },
  {
    id: "texture_01",
    file: "audio/organic_textures/texture_01.mp3",
    category: "organic_textures",
    volume: 0.36,
    fadeIn: 8,
    fadeOut: 12,
    playbackRateMin: 0.88,
    playbackRateMax: 1.06,
    panMin: -0.75,
    panMax: 0.75,
    lowpassMin: 1400,
    lowpassMax: 4200,
    highpassMin: 50,
    highpassMax: 180,
    reverbSend: 0.38,
    delaySend: 0.14,
    saturation: 0.24,
    randomStartOffset: 0.2,
    weight: 5,
    cooldown: 24,
    loop: true,
    minDuration: 18,
    maxDuration: 42,
    tags: ["wet", "flesh"],
    archetype: "filtered_noise"
  },
  {
    id: "breath_01",
    file: "audio/breaths/breath_01.mp3",
    category: "breaths",
    volume: 0.4,
    fadeIn: 3,
    fadeOut: 8,
    playbackRateMin: 0.92,
    playbackRateMax: 1.08,
    panMin: -0.45,
    panMax: 0.45,
    lowpassMin: 1200,
    lowpassMax: 4000,
    highpassMin: 90,
    highpassMax: 240,
    reverbSend: 0.26,
    delaySend: 0.04,
    saturation: 0.18,
    randomStartOffset: 0,
    weight: 4,
    cooldown: 18,
    loop: false,
    minDuration: 6,
    maxDuration: 15,
    tags: ["human", "threshold"],
    archetype: "breath"
  },
  {
    id: "choir_01",
    file: "audio/choirs/choir_01.mp3",
    category: "choirs",
    volume: 0.3,
    fadeIn: 9,
    fadeOut: 16,
    playbackRateMin: 0.96,
    playbackRateMax: 1.04,
    panMin: -0.24,
    panMax: 0.24,
    lowpassMin: 1200,
    lowpassMax: 5200,
    highpassMin: 40,
    highpassMax: 110,
    reverbSend: 0.82,
    delaySend: 0.18,
    saturation: 0.12,
    randomStartOffset: 0.1,
    weight: 3,
    cooldown: 34,
    loop: false,
    minDuration: 18,
    maxDuration: 34,
    tags: ["choral", "distant"],
    archetype: "choir"
  },
  {
    id: "interference_01",
    file: "audio/interference/interference_01.mp3",
    category: "interference",
    volume: 0.26,
    fadeIn: 1,
    fadeOut: 3,
    playbackRateMin: 0.85,
    playbackRateMax: 1.15,
    panMin: -1,
    panMax: 1,
    lowpassMin: 2600,
    lowpassMax: 7800,
    highpassMin: 250,
    highpassMax: 1200,
    reverbSend: 0.15,
    delaySend: 0.12,
    saturation: 0.32,
    randomStartOffset: 0,
    weight: 3,
    cooldown: 14,
    loop: false,
    minDuration: 4,
    maxDuration: 10,
    tags: ["machine", "static"],
    archetype: "interference"
  },
  {
    id: "pulse_01",
    file: "audio/pulses/pulse_01.mp3",
    category: "pulses",
    volume: 0.33,
    fadeIn: 1,
    fadeOut: 4,
    playbackRateMin: 0.92,
    playbackRateMax: 1.12,
    panMin: -0.5,
    panMax: 0.5,
    lowpassMin: 700,
    lowpassMax: 2200,
    highpassMin: 30,
    highpassMax: 180,
    reverbSend: 0.2,
    delaySend: 0.22,
    saturation: 0.28,
    randomStartOffset: 0,
    weight: 4,
    cooldown: 16,
    loop: false,
    minDuration: 5,
    maxDuration: 11,
    tags: ["heartbeat", "ritmic"],
    archetype: "pulse"
  },
  {
    id: "melody_01",
    file: "audio/melodic_fragments/melody_01.mp3",
    category: "melodic_fragments",
    volume: 0.27,
    fadeIn: 4,
    fadeOut: 9,
    playbackRateMin: 0.95,
    playbackRateMax: 1.08,
    panMin: -0.35,
    panMax: 0.35,
    lowpassMin: 1200,
    lowpassMax: 4200,
    highpassMin: 80,
    highpassMax: 220,
    reverbSend: 0.58,
    delaySend: 0.3,
    saturation: 0.14,
    randomStartOffset: 0,
    weight: 2,
    cooldown: 32,
    loop: false,
    minDuration: 12,
    maxDuration: 24,
    tags: ["memory", "glow"],
    archetype: "melodic"
  },
  {
    id: "ritual_01",
    file: "audio/rituals/ritual_01.mp3",
    category: "rituals",
    volume: 0.24,
    fadeIn: 0,
    fadeOut: 8,
    playbackRateMin: 0.9,
    playbackRateMax: 1.05,
    panMin: -0.6,
    panMax: 0.6,
    lowpassMin: 900,
    lowpassMax: 3400,
    highpassMin: 110,
    highpassMax: 480,
    reverbSend: 0.48,
    delaySend: 0.12,
    saturation: 0.2,
    randomStartOffset: 0,
    weight: 2,
    cooldown: 38,
    loop: false,
    minDuration: 7,
    maxDuration: 16,
    tags: ["bell", "ritual"],
    archetype: "ritual"
  }
];
